<?php
$candleUrl = 'http://www.templarknightsmc.com/wp-content/uploads/2014/08/Candle_Transparent.png';
$imgSrc = '<img src="'.$candleUrl.'" width="77" height="77" align="top" />';
echo '<table><tbody><tr><td style="vertical-align: top;" width="35%">';
echo '<div id="doc" style="text-align: center;"><center>'.$imgSrc.'</center>';
echo '<h3><b>Roger "Doc" Belt</b></h3>';
echo '<p>1951 - 2013<br />Ohio 171</p></div>';
echo '<div id="big_bird" style="text-align: center;"><center>'.$imgSrc.'</center>';
echo '<h3><b>Matthew "Big Bird" Edwards</b></h3>';
echo '<p>1994 - 2014<br />Indiana</p></div>';
echo '<div id="crowbar" style="text-align: center;"><center>'.$imgSrc.'</center>';
echo '<h3><b>Peter "Crowbar" Dahlin</b></h3>';
echo '<p>1959 - 2017<br />Stockholm</p></div></td>';
echo '<td><div id="poem" style="text-align: center;"><b>CAN YOU FEEL THE WIND IN HEAVEN</b><br />';
echo 'Can you feel the wind in Heaven?<br />Can you hear me call your name?<br />Can you see the tears that fall?<br />';
echo 'This world won\'t ever be the same.Can you feel the wind in Heaven?<br />When we gather in our group<br />';
echo 'Can you hear the sound of silence<br /> When we look where you once stood?';
echo '<p>Can you feel the wind in Heaven?<br />Can you hear the ladies cry?<br />Can you feel our broken hearts<br />';
echo 'When we have to say goodbye?</p>';
echo '<p>Can you feel the wind in Heaven?<br />While the men hold back the tears,<br />Leather clad and watery eyes<br />';
echo 'And know we’d rather have you here?</p>';
echo '<p>I hope there is a Biker Heaven<br />And we will meet again someday.<br />I hope to feel the wind in Heaven<br />';
echo 'And shake your hand again that day.</p><p>-Koolness</p>';
echo '<p><center><img src="http://www.templarknightsmc.com/wp-content/uploads/2014/08/KneelingTemplarRight.png" width="150" height="150" /></p></div></td>';
echo '<td style="vertical-align: top;" width="35%">';
echo '<div id="poppa" style="text-align: center;"><center>'.$imgSrc.'</center>';
echo '<h3><b>Bruce "Poppa" Bigras</b></h3>';
echo '<p>1954 - 2013<br />Renfrew</p></div>';
echo '<div id="cruz" style="text-align: center;"><center>'.$imgSrc.'</center>';
echo '<h3><b>Andy "Cruz" Moss</b></h3>';
echo '<p>1984 - 2015<br />Arizona</p></div></td>';
echo '</tr></tbody></table>';
?>